name: CI

on:
  push:
    branches:
      - dev
      - master
  pull_request:
    branches:
      - dev

jobs:

  lint-check:
    name: Run pre-commit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - uses: pre-commit/action@v3.0.0

  linux:
    name: Build Linux wheels
    needs: [ lint-check ]
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: |
          3.7
          3.8
          3.9
          3.10
          3.11
    - uses: abatilo/actions-poetry@v2
    - name: Build wheels
      run: poetry build
    - name: Upload wheels
      uses: actions/upload-artifact@v3
      with:
        name: wheels
        path: dist

  linux-cross:
    name: Build Linux wheels
    needs: [ lint-check ]
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        target: [i686, s390x, ppc64, ppc64le, aarch64, armv7l]
    steps:
    - uses: actions/checkout@v3
    - uses: abatilo/actions-poetry@v2
    - name: Build wheels
      run: poetry build
    - name: Upload wheels
      uses: actions/upload-artifact@v3
      with:
        name: wheels
        path: dist

  linux-musl:
    name: Build Linux musl wheels
    needs: [ lint-check ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64, aarch64, i686, armv7l]
    steps:
    - uses: actions/checkout@v3
    - uses: abatilo/actions-poetry@v2
    - name: Build wheels
      run: poetry build
    - name: Upload wheels
      uses: actions/upload-artifact@v3
      with:
        name: wheels
        path: dist

  linux-legacy:
    name: Build Linux legacy wheels
    needs: [ lint-check ]
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        target: [x86_64, s390x, ppc64le, aarch64]
    steps:
    - uses: actions/checkout@v3
    - uses: abatilo/actions-poetry@v2
    - name: Build wheels
      run: poetry build
    - name: Upload wheels
      uses: actions/upload-artifact@v3
      with:
        name: wheels
        path: dist

  windows:
    name: Build Windows wheels
    needs: [ lint-check ]
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: |
          3.7
          3.8
          3.9
          3.10
          3.11
    - uses: abatilo/actions-poetry@v2
    - name: Build wheels
      run: poetry build
    - name: Upload wheels
      uses: actions/upload-artifact@v3
      with:
        name: wheels
        path: dist

  macos:
    name: Build MacOS wheels
    needs: [ lint-check ]
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: |
          3.7
          3.8
          3.9
          3.10
          3.11
    - uses: abatilo/actions-poetry@v2
    - name: Build wheels
      run: poetry build
    - name: Upload wheels
      uses: actions/upload-artifact@v3
      with:
        name: wheels
        path: dist

  release:
    needs: [ macos, windows, linux, linux-cross, linux-musl ]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: wheels
          path: dist

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
